USE [TOKStk_DB]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

DROP	TABLE	USERID
GO

CREATE	TABLE	USERID
		(
			USER_ID 	VARCHAR(10) NOT NULL,		
			USER_PW		VARCHAR(30) NOT NULL,					
			USER_NM		VARCHAR(10),
                        USER_JNO        VARCHAR(14),
			USER_KIND       NUMERIC(2) DEFAULT(1),
			USER_USES       VARCHAR(01) DEFAULT(''),
                        USER_WDATE	SMALLDATETIME  Default (getdate()),
			CONSTRAINT	PK_STK1_USERID	PRIMARY	KEY(USER_ID)		
		)
GO	

 
INSERT INTO USERID ( USER_ID, USER_PW, USER_NM,USER_JNO, USER_KIND ) VALUES ( 'admin', '1', 'Super User', '750329-1169511', 50 );
INSERT INTO USERID ( USER_ID, USER_PW, USER_NM,USER_JNO, USER_KIND ) VALUES ( '1', '1', 'Super User', '750329-1169511', 50 );
GO

SELECT * FROM USERID
GO

SET ANSI_PADDING OFF


